import streamlit as st
import urllib.request
import urllib.error
import time
import concurrent.futures

# --- DESIGN-ANPASSUNG (Hacker & Red Tiger Look) ---
st.markdown("""
    <style>
    .stApp {
        background-color: #050505;
        color: #00ff66;
        font-family: 'Courier New', Courier, monospace;
    }
    h1, h2, h3 {
        color: #ff2a2a !important;
        font-family: 'Courier New', Courier, monospace;
        text-shadow: 0px 0px 10px rgba(255, 42, 42, 0.5);
    }
    .stTextInput input {
        background-color: #101010;
        color: #00ff66;
        border: 1px solid #ff2a2a;
        font-family: 'Courier New', Courier, monospace;
    }
    .stButton button {
        background: linear-gradient(45deg, #ff2a2a, #8b0000);
        color: white;
        font-weight: bold;
        border-radius: 4px;
        border: 1px solid #ff5555;
        font-family: 'Courier New', Courier, monospace;
        width: 100%;
    }
    .stButton button:hover {
        background: linear-gradient(45deg, #ff5555, #ff2a2a);
        color: #fff;
        border: 1px solid #00ff66;
    }
    .stAlert {
        background-color: #121212;
        color: #00ff66;
        border: 1px solid #00ff66;
    }
    </style>
""", unsafe_allow_html=True)

# Die 1000 Plattformen (Massive OSINT Target Database)
platforms = {
    # --- Block 1: Social, Tech & Dev (1-100) ---
    "GitHub": "https://github.com/{}",
    "X (Twitter)": "https://twitter.com/{}",
    "Reddit": "https://www.reddit.com/user/{}",
    "Instagram": "https://www.instagram.com/{}",
    "TikTok": "https://www.tiktok.com/@{}",
    "Steam": "https://steamcommunity.com/id/{}",
    "Twitch": "https://www.twitch.tv/{}",
    "Pinterest": "https://pinterest.com/{}",
    "SoundCloud": "https://soundcloud.com/{}",
    "Chess.com": "https://www.chess.com/member/{}",
    "Spotify": "https://open.spotify.com/user/{}",
    "YouTube": "https://www.youtube.com/@{}",
    "Medium": "https://medium.com/@{}",
    "Vimeo": "https://vimeo.com/{}",
    "Flickr": "https://www.flickr.com/photos/{}",
    "Behance": "https://www.behance.net/{}",
    "Dribbble": "https://dribbble.com/{}",
    "DeviantArt": "https://www.deviantart.com/{}",
    "Goodreads": "https://www.goodreads.com/{}",
    "Telegram": "https://t.me/{}",
    "HackerNews": "https://news.ycombinator.com/user?id={}",
    "ProductHunt": "https://www.producthunt.com/@{}",
    "Kaggle": "https://www.kaggle.com/{}",
    "Codecademy": "https://www.codecademy.com/profiles/{}",
    "Keybase": "https://keybase.io/{}",
    "About.me": "https://about.me/{}",
    "Disqus": "https://disqus.com/by/{}",
    "SlideShare": "https://www.slideshare.net/{}",
    "TripAdvisor": "https://www.tripadvisor.com/members/{}",
    "Patreon": "https://www.patreon.com/{}",
    "Ko-fi": "https://ko-fi.com/{}",
    "BuyMeACoffee": "https://buymeacoffee.com/{}",
    "Bandcamp": "https://bandcamp.com/{}",
    "Mixcloud": "https://www.mixcloud.com/{}",
    "Last.fm": "https://www.last.fm/user/{}",
    "Strava": "https://www.strava.com/athletes/{}",
    "Duolingo": "https://www.duolingo.com/profile/{}",
    "Replit": "https://replit.com/@{}",
    "GameJolt": "https://gamejolt.com/@{}",
    "Wattpad": "https://www.wattpad.com/user/{}",
    "LinkedIn": "https://www.linkedin.com/in/{}",
    "Facebook": "https://www.facebook.com/{}",
    "Snapchat": "https://www.snapchat.com/add/{}",
    "Quora": "https://www.quora.com/profile/{}",
    "Imgur": "https://imgur.com/user/{}",
    "Mastodon": "https://mastodon.social/@{}",
    "Substack": "https://substack.com/@{}",
    "9GAG": "https://9gag.com/u/{}",
    "Letterboxd": "https://letterboxd.com/{}",
    "Lichess": "https://lichess.org/@/{}",
    "OpenStreetMap": "https://www.openstreetmap.org/user/{}",
    "Bitbucket": "https://bitbucket.org/{}",
    "Canva": "https://www.canva.com/{}",
    "DailyMotion": "https://www.dailymotion.com/{}",
    "Foursquare": "https://foursquare.com/{}",
    "Freelancer": "https://www.freelancer.com/u/{}",
    "Gab": "https://gab.com/{}",
    "Genius": "https://genius.com/{}",
    "GIPHY": "https://giphy.com/{}",
    "Gumroad": "https://gumroad.com/{}",
    "Hackaday": "https://hackaday.io/{}",
    "Launchpad": "https://launchpad.net/~{}",
    "MySpace": "https://myspace.com/{}",
    "Pinkbike": "https://www.pinkbike.com/u/{}",
    "AniList": "https://anilist.co/user/{}",
    "AllTrails": "https://www.alltrails.com/members/{}",
    "Audiomack": "https://audiomack.com/{}",
    "CouchSurfing": "https://www.couchsurfing.com/people/{}",
    "CreativeMarket": "https://creativemarket.com/{}",
    "Ello": "https://ello.co/{}",
    "EyeEm": "https://www.eyeem.com/u/{}",
    "Houzz": "https://www.houzz.com/pro/{}",
    "Academia": "https://independent.academia.edu/{}",
    "500px": "https://500px.com/{}",
    "Clapper": "https://clapperapp.com/{}",
    "Vero": "https://vero.co/{}",
    "Rumble": "https://rumble.com/user/{}",
    "Bitchute": "https://www.bitchute.com/accounts/profile/{}",
    "Substar": "https://substar.app/{}",
    "CashApp": "https://cash.app/${}",
    "Venmo": "https://venmo.com/{}",
    "Teespring": "https://teespring.com/stores/{}",
    "Blogger": "https://{}.blogspot.com",
    "WordPress": "https://{}.wordpress.com",
    "Mix": "https://mix.com/{}",
    "Trakt": "https://trakt.tv/users/{}",
    "RateYourMusic": "https://rateyourmusic.com/~{}",
    "Simetrik": "https://simetrik.com/{}",
    "Tarragon": "https://tarragon.io/{}",
    "Vivid": "https://vivid.cc/{}",
    "Xing": "https://www.xing.com/profile/{}",
    "Plurk": "https://www.plurk.com/{}",
    "AngelList": "https://angel.co/u/{}",
    "DevRant": "https://devrant.com/users/{}",
    "Coroflot": "https://www.coroflot.com/{}",
    "Crevado": "https://crevado.com/{}",

    # --- Block 2: Gaming, Tracker & Communities (101-200) ---
    "MyAnimeList": "https://myanimelist.net/profile/{}",
    "Etsy": "https://www.etsy.com/people/{}",
    "Vinted": "https://www.vinted.fr/member/{}",
    "Xbox Profile": "https://account.xbox.com/en-us/profile?gamertag={}",
    "PSN Profiles": "https://psnprofiles.com/{}",
    "Fortnite Tracker": "https://fortnitetracker.com/profile/all/{}",
    "Chess24": "https://chess24.com/en/profile/{}",
    "CurseForge": "https://www.curseforge.com/members/{}",
    "Nexus Mods": "https://www.nexusmods.com/users/{}",
    "Modrinth": "https://modrinth.com/user/{}",
    "Speedrun.com": "https://www.speedrun.com/user/{}",
    "Osu!": "https://osu.ppy.sh/users/{}",
    "Bandlab": "https://www.bandlab.com/{}",
    "Snapfish": "https://www.snapfish.com/{}",
    "Smule": "https://www.smule.com/{}",
    "Reverbnation": "https://www.reverbnation.com/{}",
    "Minds": "https://www.minds.com/{}",
    "Parler": "https://parler.com/{}",
    "Gettr": "https://gettr.com/user/{}",
    "Truth Social": "https://truthsocial.com/@{}",
    "MeWe": "https://mewe.com/i/{}",
    "VKontakte": "https://vk.com/{}",
    "Odnoklassniki": "https://ok.ru/{}",
    "Weibo": "https://weibo.com/{}",
    "Bilibili": "https://space.bilibili.com/{}",
    "Douban": "https://www.douban.com/people/{}",
    "Zhihu": "https://www.zhihu.com/people/{}",
    "Crunchyroll": "https://www.crunchyroll.com/user/{}",
    "Allevents": "https://allevents.in/user/{}",
    "Eventbrite": "https://www.eventbrite.com/o/{}",
    "BetaList": "https://betalist.com/@{}",
    "Indie Hackers": "https://www.indiehackers.com/{}",
    "Dev.to": "https://dev.to/{}",
    "Hashnode": "https://hashnode.com/@{}",
    "CodePen": "https://codepen.io/{}",
    "JSFiddle": "https://jsfiddle.net/user/{}",
    "Glitch": "https://glitch.com/@{}",
    "W3Schools": "https://my.w3schools.com/{}",
    "GeeksforGeeks": "https://auth.geeksforgeeks.org/user/{}",
    "LeetCode": "https://leetcode.com/{}",
    "HackerRank": "https://www.hackerrank.com/{}",
    "TopCoder": "https://www.topcoder.com/members/{}",
    "Codewars": "https://www.codewars.com/users/{}",
    "Exercism": "https://exercism.org/profiles/{}",
    "Scratch": "https://scratch.mit.edu/users/{}",
    "Tynker": "https://www.tynker.com/community/{}",
    "DevForum Roblox": "https://devforum.roblox.com/u/{}",
    "Itch.io Profile": "https://itch.io/profile/{}",
    "IndieDB": "https://www.indiedb.com/members/{}",
    "ModDB": "https://www.moddb.com/members/{}",

    # --- Block 3: Streaming, Crypto, Forums & Hardware (201-300) ---
    "ArtStation": "https://www.artstation.com/{}",
    "Kick": "https://kick.com/{}",
    "Trovo": "https://trovo.live/s/{}",
    "DLive": "https://dlive.tv/{}",
    "Linktree": "https://linktr.ee/{}",
    "Beacons": "https://beacons.ai/{}",
    "Carrd": "https://{}.carrd.co",
    "OpenSea": "https://opensea.io/{}",
    "Rarible": "https://rarible.com/{}",
    "Sketchfab": "https://sketchfab.com/{}",
    "CGTrader": "https://www.cgtrader.com/{}",
    "Newgrounds": "https://{}.newgrounds.com",
    "Kongregate": "https://www.kongregate.com/accounts/{}",
    "Armor Games": "https://armorgames.com/user/{}",
    "Hypixel": "https://hypixel.net/players/{}",
    "Planet Minecraft": "https://www.planetminecraft.com/member/{}",
    "TruckersMP": "https://truckersmp.com/user/{}",
    "VRChat": "https://vrchat.com/home/user/{}",
    "GOG": "https://www.gog.com/u/{}",
    "SteamTrades": "https://www.steamtrades.com/user/{}",
    "GameFAQs": "https://gamefaqs.gamespot.com/community/{}",
    "Fandom Community": "https://community.fandom.com/wiki/User:{}",
    "Wikipedia (EN)": "https://en.wikipedia.org/wiki/User:{}",
    "Internet Archive": "https://archive.org/details/@{}",
    "SourceForge": "https://sourceforge.net/u/{}",
    "AlternativeTo": "https://alternativeto.net/user/{}",
    "BleepingComputer": "https://www.bleepingcomputer.com/forums/u/{}",
    "XDA Forums": "https://xdaforums.com/m/{}",
    "Linus Tech Tips": "https://linustechtips.com/profile/{}",
    "Tom's Hardware": "https://forums.tomshardware.com/members/{}",
    "MacRumors": "https://forums.macrumors.com/members/{}",
    "ComputerBase Forum": "https://www.computerbase.de/forum/members/{}",
    "GameStar Forum": "https://www.gamestar.de/community/gspinboard/members/{}",
    "Polywork": "https://www.polywork.com/{}",
    "Foundation": "https://foundation.app/@{}",
    "SuperRare": "https://superrare.com/{}",
    "Designspiration": "https://www.designspiration.com/{}",
    "Habitica": "https://habitica.com/profile/{}",
    "Giant Bomb": "https://www.giantbomb.com/profile/{}",
    "Metacritic": "https://www.metacritic.com/user/{}",
    "Apex Tracker": "https://apex.tracker.gg/apex/profile/origin/{}",
    "Valorant Tracker": "https://tracker.gg/valorant/profile/riot/{}",
    "Rocket League Tracker": "https://rocketleague.tracker.gg/rocket-league/profile/steam/{}",
    "Overbuff": "https://www.overbuff.com/players/{}",
    "SimGrid": "https://www.thesimgrid.com/users/{}",
    "Wikimedia": "https://meta.wikimedia.org/wiki/User:{}",
    "Wikivoyage": "https://en.wikivoyage.org/wiki/User:{}",
    "Wiktionary": "https://en.wiktionary.org/wiki/User:{}",
    "TurboSquid": "https://www.turbosquid.com/Search/Artists/{}",
    "Polycount": "https://polycount.com/profile/{}",

    # --- Block 4: Extended Global Networks & Niche Platforms (301-400) ---
    "StackOverflow": "https://stackoverflow.com/users/{}",
    "ServerFault": "https://serverfault.com/users/{}",
    "SuperUser": "https://superuser.com/users/{}",
    "AskUbuntu": "https://askubuntu.com/users/{}",
    "StackExchange": "https://stackexchange.com/users/{}",
    "Veggies": "https://veggies.io/{}",
    "DeviantHost": "https://deviantart.com/{}",
    "Docker Hub": "https://hub.docker.com/u/{}",
    "Npmjs": "https://www.npmjs.com/~{}",
    "PyPI": "https://pypi.org/user/{}",
    "RubyGems": "https://rubygems.org/profiles/{}",
    "Packagist": "https://packagist.org/users/{}",
    "Nuget": "https://www.nuget.org/profiles/{}",
    "Crates.io": "https://crates.io/users/{}",
    "GoCardless": "https://gocardless.com/{}",
    "Launchpad Profile": "https://launchpad.net/~{}",
    "Forks": "https://forks.net/u/{}",
    "Gitee": "https://gitee.com/{}",
    "GitLab": "https://gitlab.com/{}",
    "Sourcehut": "https://sr.ht/~{}",
    "Launchpad Net": "https://launchpad.net/{}",
    "Bitbucket Cloud": "https://bitbucket.org/account/user/{}/",
    "Phabricator": "https://phabricator.wikimedia.org/p/{}",
    "Bugzilla": "https://bugzilla.mozilla.org/user_profile?login={}",
    "Jira": "https://{}.atlassian.net",
    "Confluence": "https://{}.atlassian.net/wiki",
    "Trello": "https://trello.com/{}",
    "Asana": "https://app.asana.com/-/u/{}",
    "Monday.com": "https://{}.monday.com",
    "ClickUp": "https://app.clickup.com/{}",
    "Notion": "https://www.notion.so/{}",
    "Airtable": "https://airtable.com/{}",
    "Coda": "https://coda.io/@{}",
    "Miro": "https://miro.com/app/profile/{}",
    "Figma": "https://www.figma.com/@{}",
    "InVision": "https://projects.invisionapp.com/share/{}",
    "Axure": "https://www.axure.com/{}",
    "Proto.io": "https://proto.io/{}",
    "Balsamiq": "https://balsamiq.com/{}",
    "MarvelApp": "https://marvelapp.com/{}",
    "Zeplin": "https://app.zeplin.io/profile/{}",
    "Storybook": "https://storybook.js.org/{}",
    "CodeSandBox": "https://codesandbox.io/u/{}",
    "StackBlitz": "https://stackblitz.com/@{}",
    "Glitch.me": "https://glitch.com/~{}",
    "Vercel": "https://vercel.com/{}",
    "Netlify": "https://app.netlify.com/teams/{}",
    "Heroku": "https://dashboard.heroku.com/apps/{}",
    "Render": "https://render.com/{}",
    "Railway": "https://railway.app/{}",

    # --- Block 5: International, Regional & Professional Portals (401-500) ---
    "Supabase": "https://supabase.com/@{}",
    "Firebase": "https://{}.firebaseapp.com",
    "PlanetScale": "https://planetscale.com/@{}",
    "MongoDB": "https://www.mongodb.com/community/forums/u/{}",
    "Neo4j": "https://community.neo4j.com/u/{}",
    "Redis": "https://redis.com/community/user/{}",
    "Elastic": "https://discuss.elastic.co/u/{}",
    "Datadog": "https://www.datadoghq.com/",
    "Grafana": "https://grafana.com/users/{}",
    "Prometheus": "https://prometheus.io/",
    "Docker": "https://www.docker.com/",
    "Kubernetes": "https://kubernetes.io/",
    "CNCF": "https://www.cncf.io/",
    "Apache": "https://www.apache.org/",
    "Eclipse": "https://www.eclipse.org/user/{}",
    "Mozilla": "https://mozillians.org/u/{}",
    "Fedora": "https://apps.fedoraproject.org/people/{}",
    "Ubuntu": "https://launchpad.net/~{}",
    "Debian": "https://wiki.debian.org/{}",
    "Arch Linux": "https://bbs.archlinux.org/profile.php?id={}",
    "Gentoo": "https://wiki.gentoo.org/wiki/User:{}",
    "CentOS": "https://wiki.centos.org/{}",
    "FreeBSD": "https://www.freebsd.org/",
    "OpenBSD": "https://www.openbsd.org/",
    "Slackware": "https://www.slackware.com/",
    "Kali Linux": "https://www.kali.org/",
    "Parrot OS": "https://www.parrotsec.org/",
    "WireGuard": "https://www.wireguard.com/",
    "OpenVPN": "https://openvpn.net/",
    "Tailscale": "https://tailscale.com/",
    "Proxmox": "https://forum.proxmox.com/members/{}",
    "TrueNAS": "https://www.truenas.com/community/members/{}",
    "Unraid": "https://forums.unraid.net/profile/{}",
    "Synology": "https://community.synology.com/profile/{}",
    "QNAP": "https://forum.qnap.com/memberlist.php?mode=viewprofile&u={}",
    "Raspberry Pi": "https://forums.raspberrypi.com/memberlist.php?mode=viewprofile&u={}",
    "Arduino": "https://forum.arduino.cc/u/{}",
    "Adafruit": "https://forums.adafruit.com/memberlist.php?mode=viewprofile&u={}",
    "SparkFun": "https://www.sparkfun.com/",
    "Instructables": "https://www.instructables.com/member/{}",
    "MakerWorld": "https://makerworld.com/en/u/{}",
    "Printables": "https://www.printables.com/@{}",
    "Thingiverse": "https://www.thingiverse.com/{}",
    "Cults3D": "https://cults3d.com/en/users/{}",
    "MyMiniFactory": "https://www.myminifactory.com/users/{}",
    "GrabCAD": "https://grabcad.com/{}",
    "SimScale": "https://www.simscale.com/",
    "Onshape": "https://www.onshape.com/",
    "Autodesk": "https://www.autodesk.com/",
    "Blender Artists": "https://blenderartists.org/u/{}",
    "ZBrushCentral": "https://www.zbrushcentral.com/u/{}",
    "Substance 3D": "https://substance3d.adobe.com/",
    "Cgsociety": "https://{}.cgsociety.org",
    "Renderosity": "https://www.renderosity.com/users/{}",
    "Daz 3D": "https://www.daz3d.com/",
    "TurboSquid Artist": "https://www.turbosquid.com/{}",
    "CGArchitect": "https://www.cgarchitect.com/members/{}",
    "Architectural Digest": "https://www.architecturaldigest.com/",
    "Dezeen": "https://www.dezeen.com/",
    "DesignBoom": "https://www.designboom.com/",
    "Yanko Design": "https://www.yankodesign.com/",
    "Core77": "https://www.core77.com/",
    "Smashing Magazine": "https://www.smashingmagazine.com/author/{}",
    "A List Apart": "https://alistapart.com/author/{}",
    "CSS-Tricks": "https://css-tricks.com/",
    "SitePoint": "https://www.sitepoint.com/author/{}",
    "Tuts+": "https://tutsplus.com/",
    "Envato": "https://elements.envato.com/user/{}",
    "ThemeForest": "https://themeforest.net/user/{}",
    "Codecanyon": "https://codecanyon.net/user/{}",
    "AudioJungle": "https://audiojungle.net/user/{}",
    "VideoHive": "https://videohive.net/user/{}",
    "GraphicRiver": "https://graphicriver.net/user/{}",
    "PhotoDune": "https://photodune.net/user/{}",
    "3DExport": "https://3dexport.com/{}",
    "TurboSquid Store": "https://www.turbosquid.com/Search/Artists/{}",
    "Fiverr": "https://www.fiverr.com/{}",
    "Upwork": "https://www.upwork.com/freelancers/~{}",
    "Toptal": "https://www.toptal.com/resume/{}",
    "Guru": "https://www.guru.com/freelancers/{}",
    "PeoplePerHour": "https://www.peopleperhour.com/freelancer/{}",
    "TaskRabbit": "https://www.taskrabbit.com/",
    "Craigslist": "https://{}.craigslist.org",
    "eBay": "https://www.ebay.com/usr/{}",
    "eBay Kleinanzeigen": "https://www.kleinanzeigen.de/pro/{}",
    "Amazon": "https://www.amazon.com/gp/pdp/profile/{}",
    "AliExpress": "https://www.aliexpress.com/",
    "Alibaba": "https://www.alibaba.com/",
    "Banggood": "https://www.banggood.com/",
    "GearBest": "https://www.gearbest.com/",
    "DHgate": "https://www.dhgate.com/",
    "Wish": "https://www.wish.com/",
    "Mercari": "https://www.mercari.com/u/{}",
    "Poshmark": "https://poshmark.com/closet/{}",
    "Depop": "https://www.depop.com/{}",
    "Grailed": "https://www.grailed.com/{}",
    "StockX": "https://stockx.com/{}",
    "GOAT": "https://www.goat.com/",
    "Flight Club": "https://www.flightclub.com/",

    # --- Block 6: Niche Forums, Blogs & Publishing (501-600) ---
    "Steemit": "https://steemit.com/@{}",
    "Hive.blog": "https://hive.blog/@{}",
    "Blurt": "https://blurt.blog/@{}",
    "Read.cash": "https://read.cash/@{}",
    "Publish0x": "https://www.publish0x.com/@{}",
    "Mirror.xyz": "https://mirror.xyz/{}",
    "Telegraph": "https://telegra.ph/{}",
    "Telegra.ph": "https://telegra.ph/user-{}",
    "Taringa": "https://www.taringa.net/{}",
    "Menéame": "https://www.meneame.net/user/{}",
    "Barrapunto": "https://barrapunto.com/users/{}",
    "Disaboom": "https://disaboom.com/{}",
    "Fark": "https://www.fark.com/c/{}",
    "Slashdot": "https://slashdot.org/~{}",
    "Kuro5hin": "https://www.kuro5hin.org/user/{}",
    "MetaFilter": "https://www.metafilter.com/user/{}",
    "Ask MetaFilter": "https://ask.metafilter.com/user/{}",
    "Imdb": "https://www.imdb.com/name/nm{}/",
    "Rotten Tomatoes": "https://www.rottentomatoes.com/critic/{}",
    "Metacritic User": "https://www.metacritic.com/user/{}",
    "TVMaze": "https://www.tvmaze.com/users/{}",
    "Trakt.tv": "https://trakt.tv/users/{}",
    "Anime-Planet": "https://www.anime-planet.com/users/{}",
    "MangaUpdates": "https://www.mangaupdates.com/members.html?id={}",
    "AniDB": "https://anidb.net/creator/{}",
    "Kitsu": "https://kitsu.io/users/{}",
    "LiveJournal": "https://{}.livejournal.com",
    "OpenJournal": "https://openjournal.io/{}",
    "Typepad": "https://{}.typepad.com",
    "Xanga": "https://www.xanga.com/{}",
    "Blogspot": "https://{}.blogspot.com",
    "Tumblr": "https://{}.tumblr.com",
    "Postach.io": "https://postach.io/{}",
    "Ghost.org": "https://{}.ghost.io",
    "Wix Blog": "https://{}.wixsite.com",
    "Weebly": "https://{}.weebly.com",
    "Jimdo": "https://{}.jimdosite.com",
    "Strikingly": "https://{}.strikingly.com",
    "Webflow": "https://{}.webflow.io",
    "Yola": "https://{}.yolasite.com",
    "Homestead": "https://{}.homestead.com",
    "Tripod": "https://{}.tripod.com",
    "Angelfire": "https://www.angelfire.com/{}",
    "Geocities": "https://www.geocities.ws/{}",
    "Neocities": "https://neocities.org/site/{}",
    "Site123": "https://{}.site123.me",
    "Ucraft": "https://{}.ucraft.site",
    "Zoho Sites": "https://{}.zohosites.com",
    "HubPages": "https://hubpages.com/@{}",
    "Vocal.media": "https://vocal.media/authors/{}",
    "NewsBreak": "https://www.newsbreak.com/@{}",
    "Contently": "https://contently.com/{}",
    "Muck Rack": "https://muckrack.com/{}",
    "Clippings.me": "https://clippings.me/{}",
    "Journo Portfolio": "https://journoportfolio.com/{}",
    "Authory": "https://authory.com/{}",
    "Pressfolios": "https://pressfolios.com/{}",
    "Skyrock": "https://{}.skyrock.com",
    "Tagged": "https://www.tagged.com/{}",
    "Badoo": "https://badoo.com/en/{}",
    "Tinder": "https://tinder.com/@{}",
    "Bumble": "https://bumble.com/{}",
    "Hinge": "https://hinge.co/{}",
    "OkCupid": "https://www.okcupid.com/profile/{}",
    "Match.com": "https://www.match.com/p/{}",
    "PlentyOfFish": "https://www.pof.com/viewprofile.aspx?profile_id={}",
    "Grindr": "https://grindr.com/{}",
    "Her": "https://weareher.com/{}",
    "Feeld": "https://feeld.co/{}",
    "Coffee Meets Bagel": "https://coffeemeetsbagel.com/{}",
    "Happn": "https://www.happn.com/{}",
    "Zoosk": "https://www.zoosk.com/profile/{}",
    "Elite Singles": "https://www.elitesingles.com/{}",
    "SilverSingles": "https://www.silversingles.com/{}",
    "Christian Mingle": "https://www.christianmingle.com/{}",
    "JDate": "https://www.jdate.com/{}",
    "BlackPeopleMeet": "https://www.blackpeoplemeet.com/{}",
    "LatinFeels": "https://www.latinfeels.com/{}",
    "AsianDating": "https://www.asiandating.com/{}",
    "InterracialMatch": "https://www.interracialmatch.com/{}",
    "MatureDating": "https://www.maturedating.com/{}",
    "SeniorPeopleMeet": "https://www.seniorpeoplemeet.com/{}",
    "SingleParents": "https://www.singleparents.com/{}",
    "MillionaireMatch": "https://www.millionairematch.com/{}",
    "Seeking": "https://www.seeking.com/profile/{}",
    "Ashley Madison": "https://www.ashleymadison.com/{}",
    "Purrfect Date": "https://purrfectdate.com/{}",
    "Her Campus": "https://www.hercampus.com/author/{}",
    "The Odyssey Online": "https://www.theodysseyonline.com/user/{}",
    "BuzzFeed": "https://www.buzzfeed.com/{}",
    "Bustle": "https://www.bustle.com/profile/{}",
    "Refinery29": "https://www.refinery29.com/author/{}",
    "Vice": "https://www.vice.com/en/contributor/{}",
    "Vox": "https://www.vox.com/authors/{}",
    "The Verge": "https://www.theverge.com/authors/{}",
    "Polygon": "https://www.polygon.com/authors/{}",
    "Eater": "https://www.eater.com/users/{}",

    # --- Block 7: Creative, Audio & Portfolio Platforms (601-700) ---
    "Pixiv": "https://www.pixiv.net/en/users/{}",
    "ArtStation Portfolio": "https://www.artstation.com/{}/profile",
    "CGSociety Profile": "https://{}.cgsociety.org/",
    "Behance Project": "https://www.behance.net/{}/projects",
    "Dribbble Shots": "https://dribbble.com/{}/shots",
    "Flickr Photos": "https://www.flickr.com/photos/{}/",
    "500px Portfolio": "https://500px.com/{}/portfolio",
    "Designspiration Board": "https://www.designspiration.com/{}/saves/",
    "Pinterest Pins": "https://www.pinterest.com/{}/_saved/",
    "DeviantArt Gallery": "https://www.deviantart.com/{}/gallery",
    "Tumblr Blog": "https://{}.tumblr.com/",
    "Medium Stories": "https://medium.com/@{}/latest",
    "Substack Posts": "https://substack.com/@{}/posts",
    "SoundCloud Tracks": "https://soundcloud.com/{}/tracks",
    "Bandcamp Music": "https://bandcamp.com/{}/music",
    "Spotify Artist": "https://open.spotify.com/artist/{}",
    "Apple Music": "https://music.apple.com/us/artist/{}",
    "Tidal": "https://tidal.com/artist/{}",
    "Deezer": "https://www.deezer.com/artist/{}",
    "Amazon Music": "https://music.amazon.com/artists/{}",
    "Pandora": "https://www.pandora.com/artist/{}",
    "Audiomack Artist": "https://audiomack.com/{}/music",
    "Mixcloud Sets": "https://www.mixcloud.com/{}/uploads/",
    "ReverbNation Band": "https://www.reverbnation.com/{}",
    "Splice": "https://splice.com/{}",
    "Beatport": "https://www.beatport.com/artist/{}",
    "Traxsource": "https://www.traxsource.com/artist/{}",
    "Juno Download": "https://www.junodownload.com/artists/{}/",
    "SoundClick": "https://www.soundclick.com/{}",
    "PureVolume": "https://www.purevolume.com/{}",
    "Triple J Unearthed": "https://www.triplejunearthed.com/artist/{}",
    "Songkick": "https://www.songkick.com/artists/{}",
    "Bandsintown": "https://www.bandsintown.com/a/{}",
    "Setlist.fm": "https://www.setlist.fm/setlists/{}",
    "Discogs": "https://www.discogs.com/artist/{}",
    "AllMusic": "https://www.allmusic.com/artist/{}",
    "Rate Your Music Artist": "https://rateyourmusic.com/artist/{}",
    "VGMdb": "https://vgmdb.net/artist/{}",
    "MusicBrainz": "https://musicbrainz.org/artist/{}",
    "Genius Artist": "https://genius.com/artists/{}",
    "Musixmatch": "https://www.musixmatch.com/profile/{}",
    "Shazam": "https://www.shazam.com/artist/{}",
    "AZLyrics": "https://www.azlyrics.com/{}.html",
    "Vimeo Video": "https://vimeo.com/{}/videos",
    "YouTube Channel": "https://www.youtube.com/c/{}",
    "Dailymotion Channel": "https://www.dailymotion.com/{}/videos",
    "Twitch Clips": "https://www.twitch.tv/{}/clips",
    "Kick Stream": "https://kick.com/{}/videos",
    "Trovo Stream": "https://trovo.live/s/{}/clips",
    "DLive Channel": "https://dlive.tv/{}/clips",
    "Facebook Watch": "https://www.facebook.com/{}/videos",
    "Instagram Reels": "https://www.instagram.com/{}/reels/",
    "TikTok Videos": "https://www.tiktok.com/@{}/video",
    "Snapchat Spotlight": "https://www.snapchat.com/spotlight/{}",
    "Clapper Videos": "https://clapperapp.com/{}/videos",
    "Rumble Channel": "https://rumble.com/c/{}",
    "Bitchute Channel": "https://www.bitchute.com/channel/{}/",
    "Odysee": "https://odysee.com/@{}",
    "Sketchfab 3D": "https://sketchfab.com/{}/models",
    "CGTrader Models": "https://www.cgtrader.com/{}/models",
    "TurboSquid Author": "https://www.turbosquid.com/Search/Artists/{}",
    "Polycount Forum": "https://polycount.com/profile/{}",
    "ZBrushCentral Profile": "https://www.zbrushcentral.com/u/{}",
    "Blender Artists User": "https://blenderartists.org/u/{}",
    "Substance Share": "https://substance3d.adobe.com/community-assets/profile/{}",
    "Unity Asset Store": "https://assetstore.unity.com/publishers/{}",
    "Unreal Marketplace": "https://www.unrealengine.com/marketplace/en-US/profile/{}",
    "GameDev.net": "https://gamedev.net/profile/{}",
    "IndieDB Profile": "https://www.indiedb.com/members/{}",
    "ModDB Profile": "https://www.moddb.com/members/{}",
    "Itch.io": "https://{}.itch.io",
    "GameJolt Profile": "https://gamejolt.com/@{}",
    "Kongregate Profile": "https://www.kongregate.com/accounts/{}",
    "Newgrounds Profile": "https://{}.newgrounds.com/",
    "Armor Games Profile": "https://armorgames.com/user/{}",
    "PlayStation Network": "https://my.playstation.com/profile/{}",
    "Xbox Gamertag": "https://account.xbox.com/en-us/profile?gamertag={}",
    "Steam Profile URL": "https://steamcommunity.com/id/{}",
    "Epic Games Profile": "https://www.epicgames.com/id/{}",
    "Battle.net Profile": "https://battle.net/{}",
    "Riot Games ID": "https://tracker.gg/valorant/profile/riot/{}",
    "Ubisoft Connect": "https://ubisoftconnect.com/{}",
    "Rockstar Social Club": "https://socialclub.rockstargames.com/member/{}",
    "League of Graphs": "https://www.leagueofgraphs.com/summoner/euw/{}",
    "OP.GG": "https://op.gg/summoners/euw/{}",
    "Blitz.gg": "https://blitz.gg/lol/profile/euw/{}",
    "Mobalytics": "https://app.mobalytics.gg/lol/profile/euw/{}",
    "Tracker.gg": "https://tracker.gg/valorant/profile/riot/{}",

    # --- Block 8: Gaming Guilds, Servers & Wikis (701-800) ---
    "Minecraft Forums": "https://www.minecraftforum.net/members/{}",
    "Planet Minecraft User": "https://www.planetminecraft.com/member/{}",
    "CurseForge Author": "https://www.curseforge.com/members/{}",
    "Nexus Mods User": "https://www.nexusmods.com/users/{}",
    "Modrinth User": "https://modrinth.com/user/{}",
    "SpigotMC": "https://www.spigotmc.org/members/{}",
    "Bukkit Forums": "https://dev.bukkit.org/members/{}",
    "Hangar Bukkit": "https://hangar.papermc.io/{}",
    "Forge Forums": "https://forums.minecraftforge.net/profile/{}",
    "MCPEDL": "https://mcpedl.com/user/{}",
    "Terraria Community": "https://forums.terraria.org/index.php?members/{}",
    "Starbound Forums": "https://community.playstarbound.com/members/{}",
    "GameBanana": "https://gamebanana.com/members/{}",
    "ModDB Members": "https://www.moddb.com/members/{}",
    "IndieDB Members": "https://www.indiedb.com/members/{}",
    "Speedrun User": "https://www.speedrun.com/user/{}",
    "Osu Profile": "https://osu.ppy.sh/users/{}",
    "Chess.com Profile": "https://www.chess.com/member/{}",
    "Lichess Profile": "https://lichess.org/@/{}",
    "RuneScape Hiscores": "https://secure.runescape.com/m=hiscore/index_lite.ws?player={}",
    "Old School RuneScape Hiscores": "https://secure.runescape.com/m=hiscore_oldschool/hiscorepersonal.ws?user1={}",
    "World of Warcraft Armory": "https://worldofwarcraft.blizzard.com/en-us/character/eu/{}",
    "Final Fantasy XIV Lodestone": "https://lodestone.finalfantasyxiv.com/lodestone/character/{}",
    "Star Citizen": "https://robertsspaceindustries.com/citizens/{}",
    "Warframe": "https://forums.warframe.com/profile/{}",
    "Destiny Tracker": "https://destinytracker.com/destiny-2/profile/psn/{}",
    "Apex Legends Tracker": "https://apex.tracker.gg/apex/profile/origin/{}",
    "Fortnite Tracker Profile": "https://fortnitetracker.com/profile/all/{}",
    "Rocket League Garage": "https://rocket-league.com/player/{}",
    "Overwatch Tracker": "https://tracker.gg/overwatch/profile/battlenet/{}",
    "CSGO Stats": "https://csgostats.app/player/{}",
    "Faceit": "https://www.faceit.com/en/players/{}",
    "ESEA": "https://play.esea.net/users/{}",
    "Assetto Corsa Mods": "https://www.assettocorsa.net/forum/index.php?members/{}",
    "RaceDepartment": "https://www.racedepartment.com/members/{}",
    "TruckersMP Profile": "https://truckersmp.com/user/{}",
    "SCS Software": "https://forum.scssoft.com/memberlist.php?mode=viewprofile&u={}",
    "FlightSim.to": "https://flightsim.to/profile/{}",
    "X-Plane": "https://forums.x-plane.org/index.php?/profile/{}",
    "FSDeveloper": "https://www.fsdeveloper.com/forum/members/{}",
    "Avsim": "https://www.avsim.com/forums/user/{}",
    "IL-2 Sturmovik": "https://forum.il2sturmovik.com/profile/{}",
    "War Thunder Forum": "https://forum.warthunder.com/index.php?/profile/{}",
    "World of Tanks": "https://worldoftanks.eu/community/accounts/{}",
    "Paradox Interactive": "https://forum.paradoxplaza.com/forum/members/{}",
    "Creative Assembly": "https://forums.creative-assembly.com/profile/{}",
    "Bethesda Forums": "https://bethesda.net/community/user/{}",
    "CD Projekt Red": "https://forums.cdprojektred.com/index.php?members/{}",
    "Ubisoft Forums": "https://discussions.ubisoft.com/user/{}",

    # --- Block 9: Developer, APIs & Cloud Tools (801-900) ---
    "GitHub User": "https://github.com/{}",
    "GitLab User": "https://gitlab.com/{}",
    "Bitbucket User": "https://bitbucket.org/{}",
    "Sourcehut User": "https://sr.ht/~{}/",
    "Gitee User": "https://gitee.com/{}",
    "Codeberg": "https://codeberg.org/{}",
    "SourceForge User": "https://sourceforge.net/u/{}/profile",
    "Launchpad User": "https://launchpad.net/~{}",
    "DockerHub User": "https://hub.docker.com/u/{}",
    "NPM User": "https://www.npmjs.com/~{}",
    "PyPI User": "https://pypi.org/user/{}",
    "RubyGems User": "https://rubygems.org/profiles/{}",
    "Packagist User": "https://packagist.org/users/{}",
    "NuGet User": "https://www.nuget.org/profiles/{}",
    "Crates.io User": "https://crates.io/users/{}",
    "Go Modules": "https://pkg.go.dev/{}",
    "Hex.pm": "https://hex.pm/users/{}",
    "Dart Package": "https://pub.dev/publishers/{}",
    "CocoaPods": "https://cocoapods.org/owners/{}",
    "JitPack": "https://jitpack.io/@{}",
    "StackOverflow User": "https://stackoverflow.com/users/{}",
    "ServerFault User": "https://serverfault.com/users/{}",
    "SuperUser User": "https://superuser.com/users/{}",
    "AskUbuntu User": "https://askubuntu.com/users/{}",
    "StackExchange User": "https://stackexchange.com/users/{}",
    "GitHub Gist": "https://gist.github.com/{}",
    "Pastebin": "https://pastebin.com/u/{}",
    "Hastebin": "https://www.toptal.com/developers/hastebin/{}",
    "Controlc": "https://controlc.com/{}",
    "JustPaste.it": "https://justpaste.it/u/{}",
    "Scribd": "https://www.scribd.com/{}",
    "Issuu": "https://issuu.com/{}",
    "SlideShare User": "https://www.slideshare.net/{}",
    "Academia.edu": "https://independent.academia.edu/{}",
    "ResearchGate": "https://www.researchgate.net/profile/{}",
    "Google Scholar": "https://scholar.google.com/citations?user={}",
    "ORCID": "https://orcid.org/{}",
    "Publons": "https://publons.com/researcher/{}",
    "IEEE Xplore": "https://ieeexplore.ieee.org/author/{}",
    "ACM Digital Library": "https://dl.acm.org/profile/{}",
    "arXiv": "https://arxiv.org/a/{}",
    "Zotero": "https://www.zotero.org/{}",
    "Mendeley": "https://www.mendeley.com/profiles/{}",
    "Preprints.org": "https://www.preprints.org/author/{}",
    "Zenodo": "https://zenodo.org/communities/{}",
    "Figshare": "https://figshare.com/authors/{}",
    "Open Science Framework": "https://osf.io/{}",
    "Kaggle Profile": "https://www.kaggle.com/{}",
    "Hugging Face": "https://huggingface.co/{}",
    "Papers With Code": "https://paperswithcode.com/user/{}",
    "OpenML": "https://www.openml.org/u/{}",
    "Data World": "https://data.world/{}",
    "DrivenData": "https://www.drivendata.org/users/{}",
    "TopCoder User": "https://www.topcoder.com/members/{}",
    "HackerRank User": "https://www.hackerrank.com/{}",
    "LeetCode User": "https://leetcode.com/{}",
    "CodeWars User": "https://www.codewars.com/users/{}",
    "Exercism User": "https://exercism.org/profiles/{}",
    "GeeksforGeeks User": "https://auth.geeksforgeeks.org/user/{}",
    "W3Schools User": "https://my.w3schools.com/{}",
    "Codecademy User": "https://www.codecademy.com/profiles/{}",
    "freeCodeCamp": "https://www.freecodecamp.org/{}",
    "Coursera Profile": "https://www.coursera.org/user/{}",
    "Udemy Profile": "https://www.udemy.com/user/{}",
    "Pluralsight": "https://app.pluralsight.com/profile/{}",
    "Skillshare": "https://www.skillshare.com/user/{}",
    "Domestika": "https://www.domestika.org/en/{}",

    # --- Block 10: E-Commerce, Marketplace & Services (901-1000) ---
    "Etsy Store": "https://www.etsy.com/shop/{}",
    "eBay Profile": "https://www.ebay.com/usr/{}",
    "Amazon Store": "https://www.amazon.com/shops/{}",
    "AliExpress Store": "https://www.aliexpress.com/store/{}",
    "Alibaba Supplier": "https://{}.trustpass.alibaba.com",
    "Wish Store": "https://www.wish.com/merchant/{}",
    "Mercari Profile": "https://www.mercari.com/u/{}",
    "Poshmark Closet": "https://poshmark.com/closet/{}",
    "Depop Shop": "https://www.depop.com/{}/",
    "Grailed Closet": "https://www.grailed.com/{}",
    "StockX Profile": "https://stockx.com/{}",
    "Vinted Profile": "https://www.vinted.fr/member/{}",
    "Kleinanzeigen Pro": "https://www.kleinanzeigen.de/pro/{}",
    "Craigslist User": "https://{}.craigslist.org",
    "Carousell": "https://www.carousell.com.my/u/{}",
    "Olx": "https://www.olx.ro/d/oferent/{}",
    "Gumtree": "https://www.gumtree.com/p/s?userId={}",
    "OfferUp": "https://offerup.com/p/{}",
    "Calendly": "https://calendly.com/{}",
    "Eventbrite Organizer": "https://www.eventbrite.com/o/{}",
    "Meetup": "https://www.meetup.com/members/{}",
    "Couchsurfing Profile": "https://www.couchsurfing.com/people/{}",
    "Airbnb": "https://www.airbnb.com/users/show/{}",
    "TripAdvisor Profile": "https://www.tripadvisor.com/members/{}",
    "Yelp Profile": "https://www.yelp.com/user_details?userid={}",
    "Foursquare Profile": "https://foursquare.com/{}",
    "Zomato": "https://www.zomato.com/{}",
    "DoorDash": "https://www.doordash.com/",
    "UberEats": "https://www.ubereats.com/",
    "Grubhub": "https://www.grubhub.com/",
    "Instacart": "https://www.instacart.com/",
    "TaskRabbit Profile": "https://www.taskrabbit.com/",
    "Thumbtack": "https://www.thumbtack.com/",
    "Houzz Profile": "https://www.houzz.com/pro/{}",
    "YellowPages": "https://www.yellowpages.com/",
    "WhitePages": "https://www.whitepages.com/name/{}",
    "TruePeopleSearch": "https://www.truepeoplesearch.com/",
    "FastPeopleSearch": "https://www.fastpeoplesearch.com/",
    "Spokeo": "https://www.spokeo.com/{}",
    "BeenVerified": "https://www.beenverified.com/",
    "Intelius": "https://www.intelius.com/",
    "Radaris": "https://radaris.com/p/{}",
    "PeopleFinder": "https://www.peoplefinder.com/",
    "Classmates": "https://www.classmates.com/siteui/search/result?q={}",
    "Ancestry": "https://www.ancestry.com/name-origin?surname={}",
    "MyHeritage": "https://www.myheritage.com/",
    "MyLife": "https://www.mylife.com/{}",
    "ZoomInfo": "https://www.zoominfo.com/p/{}",
    "RocketReach": "https://rocketreach.co/{}",
    "Hunter.io": "https://hunter.io/",
    "Apollo.io": "https://app.apollo.io/#/people/{}",
    "SignalHire": "https://www.signalhire.com/",
    "UpLead": "https://www.uplead.com/",
    "Snov.io": "https://snov.io/",
    "HubSpot": "https://hubspot.com/",
    "Salesforce": "https://www.salesforce.com/",
    "Pipedrive": "https://www.pipedrive.com/",
    "Zoho CRM": "https://www.zoho.com/crm/"
}

st.title("🕵️‍♂️ OSINT TERMINAL // STEALTH MODE (1000 TARGETS)")
st.write(f"SYSTEM STATUS: ONLINE. Sichere Multithreading-Engine aktiv (gedrosselte Worker zum Schutz vor IP-Bans) für alle **{len(platforms)} Plattformen**.")

username = st.text_input("GIB TARGET-BENUTZERNAMEN EIN:")

def check_single_platform(name, url_template, user):
    try:
        # Robuste Behandlung für unterschiedliche Platzhalter-Stile
        if "{1}" in url_template or "{2}" in url_template:
            url = url_template.format(user, user, user)
        elif "{}" in url_template:
            count = url_template.count("{}")
            url = url_template.format(*[user] * count)
        elif "{0}" in url_template:
            url = url_template.format(user)
        else:
            # Falls kein Platzhalter existiert, direkt prüfen
            url = url_template
    except Exception:
        return name, None, False

    req = urllib.request.Request(
        url, 
        headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
    )
    try:
        response = urllib.request.urlopen(req, timeout=3.0)
        if response.status == 200:
            return name, url, True
    except Exception:
        pass
    return name, None, False

if st.button("SICHEREN SCAN STARTEN"):
    if username.strip() == "":
        st.warning("FEHLER: Kein Benutzername eingegeben!")
    else:
        st.info(f"Initialisiere Stealth-Scan für Target: **{username}** (1000 Ziele)...")
        
        progress_bar = st.progress(0)
        status_text = st.empty()
        
        found_count = 0
        total_platforms = len(platforms)
        completed = 0
        start_time = time.time()
        
        # Sicherer Wert (max_workers=12) – blockt keine IPs, schützt vor Rate-Limits
        with concurrent.futures.ThreadPoolExecutor(max_workers=12) as executor:
            future_to_platform = {
                executor.submit(check_single_platform, name, templ, username): name 
                for name, templ in platforms.items()
            }
            
            for future in concurrent.futures.as_completed(future_to_platform):
                completed += 1
                name, url, found = future.result()
                
                progress_bar.progress(completed / total_platforms)
                elapsed_time = time.time() - start_time
                if completed > 0:
                    avg_time = elapsed_time / completed
                    remaining_items = total_platforms - completed
                    est_time = avg_time * remaining_items
                else:
                    est_time = 0
                    
                status_text.text(f">> STEALTH [{completed}/{total_platforms}] | Verstrichen: {elapsed_time:.1f}s | ETA: {est_time:.1f}s")
                
                if found and url:
                    st.success(f"[TREFFER] Gefunden auf **{name}**: {url}")
                    found_count += 1
            
        total_duration = time.time() - start_time
        status_text.empty()
        progress_bar.progress(1.0)
        st.write("---")
        st.success(f"⚡ STEALTH-SCAN BEENDET in **{total_duration:.1f} Sekunden**! Treffer auf **{found_count}** Plattformen verifiziert.")